<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OpenForgeSelf</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon" Version="2.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="NewLife.Agent" Version="10.16.2026.701" />
    <PackageReference Include="NewLife.Core" Version="11.17.2026.701" />
    <PackageReference Include="NewLife.Stardust" Version="3.9.2026.708" />
    <PackageReference Include="NewLife.XCode" Version="12.0.2026.701" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.9" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Plugins\**\plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
